### ISSUE TITLE
License

### ISSUE THREAD

**Issue by maandree** [clibs/strdup#3]
”License: MIT”, is not a sufficient way to specify the license.
There are two licenses known as ”the MIT License”, but none
if them is named ”MIT License”. Please a full LICENSE file.

**Comment by stephenmathieson** [comment]
just stop dude

**Comment by maandree** [comment]
I'm letting you know if an issue. If you intent to release your
project as free software or open source, you should let
people know which license it uses.

Either you can fix it, tell me that you do not want to fix,
or you can be rude about it. What is wrong with fully
specifying what license you use?

To fix it, the least you have to do is to specify the license,
or a link to the legal text. (Perhaps you should use the
Universal Permissive License if you are that lazy.) But you
should add the full license. Both licenses read in part:

```
The above copyright notice and this permission notice shall
be included in all copies or substantial portions of the Software.
```

This implies that you should do this.

If you do not care about the legal matters, perhaps you
should not release your software (as anything else than
proprietary software, which you of course should not do.)

**Comment by jwerle** [comment]
@maandree open ~~an issue~~ a pull request with a fix if you have an issue ! Stop trolling

**Comment by maandree** [comment]
I did open an issue. You are responding to it! ☺

**Comment by maandree** [comment]
I will not open two pull requests with two different
licenses. And try to figure out who has valid copyright,
their names and their e-mail address, and then add
the years of authorship on top of that.

**Comment by maandree** [comment]
I'm sorry if you think that submitting bug reports, legal, technical,
or otherwise, is trolling. I did this for your benefit. It has obviously
been a waste of time, although entertaining.
